function [K] = kn1n1(x, y, hyp, unx, uny, i)
global ModelInfo;

nu = ModelInfo.nu;
dt = ModelInfo.dt;

logsigma = hyp(1);
logtheta = hyp(2:end);
nn = size(x,1);


if (i==0 || i==1)
    
    K = exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta) ...
        .*bsxfun(@minus,x,y').^2).*(dt.*exp(1).^logtheta.*(unx*ones(1,nn)).*...
        (((-1).*exp(1).^(2.*logtheta)+(-3).*dt.* ...
        exp(1).^logtheta.*nu+dt.*nu.*bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y')+dt.*exp( ...
        1).^logtheta.*(exp(1).^logtheta+(-1).*bsxfun(@minus,x,y').^2).*(ones(nn,1)*uny'))+...
        (-1).*dt.*nu.*((-1).*exp(1).^(3.* ...
        logtheta)+exp(1).^(2.*logtheta).*((-3).*dt.*nu+bsxfun(@minus,x,y').^2)+ ...
        6.*dt.*exp(1).^logtheta.*nu.*bsxfun(@minus,x,y').^2+(-1).*dt.* ...
        nu.*bsxfun(@minus,x,y').^4+(-1).*dt.*exp(1).^logtheta.*(3.*exp(1) ...
        .^logtheta+(-1).*bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y').*(ones(nn,1)*uny'))+...
        exp(1).^(2.*logtheta).*(exp(1) ...
        .^(2.*logtheta)+(-1).*dt.*nu.*bsxfun(@minus,x,y').^2+dt.*exp(1) ...
        .^logtheta.*(nu+bsxfun(@minus,x,y').*(ones(nn,1)*uny'))));
    
    
    
elseif i==2
    
    K = exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta) ...
        .*bsxfun(@minus,x,y').^2).*(dt.*exp(1).^logtheta.*(unx*ones(1,nn)).*...
        (((-1).*exp(1).^(2.*logtheta)+(-3).*dt.* ...
        exp(1).^logtheta.*nu+dt.*nu.*bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y')+dt.*exp( ...
        1).^logtheta.*(exp(1).^logtheta+(-1).*bsxfun(@minus,x,y').^2).*(ones(nn,1)*uny'))+...
        dt.*exp(1).^(2.*logtheta).*(unx*ones(1,nn)).*((-1).*(2.*exp(1).^logtheta ...
        +3.*dt.*nu).*bsxfun(@minus,x,y')+dt.*(2.*exp(1).^logtheta+(-1).*bsxfun(@minus,x,y').^2).*...
        (ones(nn,1)*uny')) +(-1).*dt.* ...
        exp(1).^logtheta.*nu.*((-3).*exp(1).^(2.*logtheta)+exp(1) ...
        .^logtheta.*((-6).*dt.*nu+2.*bsxfun(@minus,x,y').^2)+6.*dt.*nu.*bsxfun(@minus,x,y').^2+...
        dt.*((-6).*exp(1).^logtheta+bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y').*...
        (ones(nn,1)*uny'))+exp(1).^(3.* ...
        logtheta).*(2.*exp(1).^logtheta+dt.*(nu+bsxfun(@minus,x,y') ...
        .*(ones(nn,1)*uny')))+2.*exp(1).^(2.* ...
        logtheta).*(exp(1).^(2.*logtheta)+(-1).*dt.*nu.*bsxfun(@minus,x,y').^2+...
        dt.*exp(1).^logtheta.*(nu+bsxfun(@minus,x,y').*(ones(nn,1)*uny')))+((-4)+(1/2).*exp(1).^((-1).*logtheta) ...
        .*bsxfun(@minus,x,y').^2).*(dt.*exp(1).^logtheta.*(unx*ones(1,nn)).*(((-1).*exp(1).^(2.*logtheta)+(-3).*dt.* ...
        exp(1).^logtheta.*nu+dt.*nu.*bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y')+dt.*exp( ...
        1).^logtheta.*(exp(1).^logtheta+(-1).*bsxfun(@minus,x,y').^2).*(ones(nn,1)*uny'))+...
        (-1).*dt.*nu.*((-1).*exp(1).^(3.* ...
        logtheta)+exp(1).^(2.*logtheta).*((-3).*dt.*nu+bsxfun(@minus,x,y').^2)+...
        6.*dt.*exp(1).^logtheta.*nu.*bsxfun(@minus,x,y').^2+(-1).*dt.* ...
        nu.*bsxfun(@minus,x,y').^4+(-1).*dt.*exp(1).^logtheta.*(3.*exp(1) ...
        .^logtheta+(-1).*bsxfun(@minus,x,y').^2).*bsxfun(@minus,x,y').*(ones(nn,1)*uny'))+...
        exp(1).^(2.*logtheta).*(exp(1) ...
        .^(2.*logtheta)+(-1).*dt.*nu.*bsxfun(@minus,x,y').^2+dt.*exp(1) ...
        .^logtheta.*(nu+bsxfun(@minus,x,y').*(ones(nn,1)*uny')))));
end

end

