function K=D4kDx2Dy2(x, y, hyp, i)

logsigma = hyp(1);
logtheta = hyp(2);

n_x = size(x,1);
n_y = size(y,1);

x = x*ones(1,n_y);
y = ones(n_x,1)*y';

if i==0
    
    K = (-6).*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*(( ...
        1+exp(1).^logsigma+exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+ ...
        exp(1).^logtheta.*y.^2)).^(-1/2).*((-1).*exp(1).^logsigma.*(1+2.* ...
        exp(1).^logsigma)+exp(1).^logtheta.*(4.*exp(1).^(2.*logsigma).*(x+ ...
        (-1).*y).^2+2.*exp(1).^logsigma.*(x+(-2).*y).*(2.*x+(-1).*y)+(-5) ...
        .*x.*y)).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+exp(1) ...
        .^logsigma.*(x+(-1).*y).^2+y.^2)).^(-3).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2);
    
elseif i== 1
    
    K = 3.*exp(1).^(logsigma+2.*logtheta).*pi.^(-1).*((1+exp(1).^logsigma+ ...
        exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.* ...
        y.^2)).^(-1/2).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+ ...
        exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-4).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2).*(2+6.*exp(1).^logsigma+(-8).*exp(1).^(3.* ...
        logsigma)+3.*exp(1).^logtheta.*(4.*exp(1).^(3.*logsigma).*(x+(-1) ...
        .*y).^2+exp(1).^logsigma.*(x.^2+(-26).*x.*y+y.^2)+(-2).*(x.^2+5.* ...
        x.*y+y.^2)+4.*exp(1).^(2.*logsigma).*(3.*x.^2+(-4).*x.*y+3.*y.^2)) ...
        +exp(1).^(2.*logtheta).*((-8).*x.^4+8.*exp(1).^(3.*logsigma).*(x+( ...
        -1).*y).^4+5.*x.^3.*y+54.*x.^2.*y.^2+5.*x.*y.^3+(-8).*y.^4+(-12).* ...
        exp(1).^(2.*logsigma).*(x+(-1).*y).^2.*(x.^2+7.*x.*y+y.^2)+(-4).* ...
        exp(1).^logsigma.*(7.*x.^4+7.*x.^3.*y+(-36).*x.^2.*y.^2+7.*x.* ...
        y.^3+7.*y.^4)));
    
elseif i== 2
    
    K = 3.*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*((1+ ...
        exp(1).^logsigma+exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp( ...
        1).^logtheta.*y.^2)).^(-1/2).*(1+2.*exp(1).^logsigma+exp(1) ...
        .^logtheta.*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-4).*( ...
        1+(-1).*(1+exp(1).^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*y.^2).^(-1)).^(-1/2).*(4.*exp(1).^logsigma.*(1+2.*exp( ...
        1).^logsigma).^2+exp(1).^(2.*logtheta).*(4.*exp(1).^(2.*logsigma) ...
        .*(x+(-1).*y).^2+2.*exp(1).^logsigma.*(x+(-2).*y).*(2.*x+(-1).*y)+ ...
        (-5).*x.*y).*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)+(-3).* ...
        exp(1).^logtheta.*(1+2.*exp(1).^logsigma).*(9.*exp(1).^(2.* ...
        logsigma).*(x+(-1).*y).^2+(-10).*x.*y+exp(1).^logsigma.*(9.*x.^2+( ...
        -20).*x.*y+9.*y.^2)));
    
end

end