function K=D3kDxDy2(x, y, hyp, i)

logsigma = hyp(1);
logtheta = hyp(2);

n_x = size(x,1);
n_y = size(y,1);

x = x*ones(1,n_y);
y = ones(n_x,1)*y';

if i==0
    
    K = 6.*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*(exp( ...
        1).^logsigma.*(x+(-1).*y)+(-1).*y).*((1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2)).^( ...
        -1/2).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+exp(1) ...
        .^logsigma.*(x+(-1).*y).^2+y.^2)).^(-2).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2);
    
elseif i== 1
    
    K = 3.*exp(1).^(logsigma+2.*logtheta).*pi.^(-1).*((1+exp(1).^logsigma+ ...
        exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.* ...
        y.^2)).^(-1/2).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+ ...
        exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-3).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2).*(4.*y+2.*(x+(-2).*exp(1).^(2.*logsigma).*(x+(-1) ...
        .*y)+exp(1).^logsigma.*(x+5.*y))+exp(1).^logtheta.*(2.*x.^3+(-2).* ...
        exp(1).^(2.*logsigma).*(x+(-1).*y).^3+(-1).*x.^2.*y+(-8).*x.*y.^2+ ...
        (-1).*y.^3+exp(1).^logsigma.*(5.*x.^3+7.*x.^2.*y+(-13).*x.*y.^2+ ...
        y.^3)));
    
elseif i== 2
    
    K = (-3).*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*( ...
        exp(1).^logsigma.*(x+(-1).*y)+(-1).*y).*((1+exp(1).^logsigma+exp( ...
        1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2)) ...
        .^(-1/2).*((-4)+(-8).*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+ ...
        exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).*(1+2.*exp(1).^logsigma+ ...
        exp(1).^logtheta.*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^( ...
        -3).*(1+(-1).*(1+exp(1).^logsigma+exp(1).^logtheta.*x.^2).^(-1).*( ...
        exp(1).^logsigma+exp(1).^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+ ...
        exp(1).^logtheta.*y.^2).^(-1)).^(-1/2);
    
end

end