function K=D3kDx2Dy(x, y, hyp, i)

logsigma = hyp(1);
logtheta = hyp(2);

n_x = size(x,1);
n_y = size(y,1);

x = x*ones(1,n_y);
y = ones(n_x,1)*y';

if i==0
    
    K = (-6).*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*( ...
        x+exp(1).^logsigma.*(x+(-1).*y)).*((1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2)).^( ...
        -1/2).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+exp(1) ...
        .^logsigma.*(x+(-1).*y).^2+y.^2)).^(-2).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2);
    
elseif i== 1
    
    K = 3.*exp(1).^(logsigma+2.*logtheta).*pi.^(-1).*((1+exp(1).^logsigma+ ...
        exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.* ...
        y.^2)).^(-1/2).*(1+2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+ ...
        exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-3).*(1+(-1).*(1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2) ...
        .^(-1)).^(-1/2).*(2.*(1+2.*exp(1).^logsigma).*(2.*x+exp(1) ...
        .^logsigma.*(x+(-1).*y)+y)+exp(1).^(logsigma+logtheta).*(x.^3+( ...
        -13).*x.^2.*y+7.*x.*y.^2+5.*y.^3+x.*(x.^2+(-14).*x.*y+5.*y.^2).* ...
        cosh(logsigma)+(3.*x.^3+2.*x.^2.*y+7.*x.*y.^2+(-4).*y.^3).*sinh( ...
        logsigma)));
    
elseif i== 2
    
    K = 3.*exp(1).^(2.*logtheta).*(1+2.*exp(1).^logsigma).*pi.^(-1).*(x+ ...
        exp(1).^logsigma.*(x+(-1).*y)).*((1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2)).^( ...
        -1/2).*((-4)+(-8).*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+exp(1) ...
        .^logsigma.*(x+(-1).*y).^2+y.^2)).*(1+2.*exp(1).^logsigma+exp(1) ...
        .^logtheta.*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-3).*( ...
        1+(-1).*(1+exp(1).^logsigma+exp(1).^logtheta.*x.^2).^(-1).*(exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.*y).^2.*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*y.^2).^(-1)).^(-1/2);
    
end

end