function K=DkDy(x, y, hyp, i)

logsigma = hyp(1);
logtheta = hyp(2);

n_x = size(x,1);
n_y = size(y,1);

x = x*ones(1,n_y);
y = ones(n_x,1)*y';

if i==0
    
    K = 2.*exp(1).^logtheta.*pi.^(-1).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).*(x+exp(1).^logsigma.*(x+(-1).*y)).*((1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*y.^2)).^(-3/2).*(1+(-1).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1).^logtheta.*x.*y) ...
        .^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2).^(-1)).^(-1/2);
    
elseif i== 1
    
    K = exp(1).^(logsigma+logtheta).*pi.^(-1).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*y.^2).^(-2).*((1+exp(1).^logsigma+exp(1).^logtheta.* ...
        x.^2).*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2)).^(-1/2).*(1+ ...
        2.*exp(1).^logsigma+exp(1).^logtheta.*(x.^2+exp(1).^logsigma.*(x+( ...
        -1).*y).^2+y.^2)).^(-1).*(1+(-1).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*x.^2).^(-1).*(exp(1).^logsigma+exp(1).^logtheta.*x.*y) ...
        .^2.*(1+exp(1).^logsigma+exp(1).^logtheta.*y.^2).^(-1)).^(-1/2).*( ...
        exp(1).^(2.*logtheta).*y.^2.*(x.^3+exp(1).^logsigma.*(x+(-1).*y) ...
        .^3+x.*y.^2+(-2).*y.^3)+exp(1).^logtheta.*((-1).*x.^3+(-1).*exp(1) ...
        .^(2.*logsigma).*(x+(-1).*y).^3+(-1).*x.*y.^2+(-4).*y.^3+(-1).* ...
        exp(1).^logsigma.*(2.*x+(-3).*y).*(x+(-1).*y).*(x+y))+(-2).*exp(1) ...
        .^logsigma.*(2.*x+y+2.*x.*cosh(logsigma)+(-2).*y.*sinh(logsigma)));
    
elseif i== 2
    
    K = exp(1).^logtheta.*pi.^(-1).*(x+exp(1).^logsigma.*(x+(-1).*y)).*(1+ ...
        exp(1).^logsigma+exp(1).^logtheta.*y.^2).^(-2).*((1+exp(1) ...
        .^logsigma+exp(1).^logtheta.*x.^2).*(1+exp(1).^logsigma+exp(1) ...
        .^logtheta.*y.^2)).^(-1/2).*(1+2.*exp(1).^logsigma+exp(1) ...
        .^logtheta.*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)).^(-1).*( ...
        2+2.*exp(1).^logsigma.*(3+2.*exp(1).^logsigma)+exp(1).^logtheta.*( ...
        1+exp(1).^logsigma).*(x.^2+exp(1).^logsigma.*(x+(-1).*y).^2+y.^2)+ ...
        (-1).*exp(1).^(2.*logtheta).*y.^2.*(x.^2+exp(1).^logsigma.*(x+(-1) ...
        .*y).^2+y.^2)).*(1+(-1).*(1+exp(1).^logsigma+exp(1).^logtheta.* ...
        x.^2).^(-1).*(exp(1).^logsigma+exp(1).^logtheta.*x.*y).^2.*(1+exp( ...
        1).^logsigma+exp(1).^logtheta.*y.^2).^(-1)).^(-1/2);
    
end

end